---
title: "Variablen"
---

# Erstmalige Aufnahme in die Warteliste

Eingabefelder in der rechten Spalte, die dem Zeitpunkt Tx = Transplantation zugeordnet werden, erscheinen erst, wenn unter Statusänderung - Neuer Status = transplantiert ausgewählt wurde. In der folgenden Tabelle ist dies nicht expliziet erwähnt, wenn es sich um Felder handelt, die es sowohl für L = Listung und Tx gibt.

# Legende

L = Listung, Tx = Transplantation, EdB = Ende der Beobachtung\

+--------------+------------------+-------------+---------------+------------------------------------------------------------------------------------------------------------------------+
| **Variable** | **Beschreibung** | **Einheit** | **Zeitpunkt** | **Hinweis**                                                                                                            |
+:=============+:=================+:============+:==============+:=======================================================================================================================+
| Datum        |                  |             | L             |                                                                                                                        |
+--------------+------------------+-------------+---------------+------------------------------------------------------------------------------------------------------------------------+
| Listenstatus |                  |             | L             | Wenn direkt mit Aufnahme auf die Warteliste ein HU-Antrag gestellt und dieser positiv entschieden wurde, HU auswählen. |
+--------------+------------------+-------------+---------------+------------------------------------------------------------------------------------------------------------------------+

# Statusänderung

+--------------+------------------+-------------+----------------------------------+-------------+
| **Variable** | **Beschreibung** | **Einheit** | **Zeitpunkt**                    | **Hinweis** |
+:=============+:=================+:============+:=================================+:============+
| Datum        |                  |             | zwischen L und Tx und / oder EdB |             |
+--------------+------------------+-------------+----------------------------------+-------------+
| Listenstatus |                  |             | zwischen L und Tx und / oder EdB |             |
+--------------+------------------+-------------+----------------------------------+-------------+

# Follow-up/ Ende der Datenerhebung

+-------------------------------------------------------+------------------+-------------+---------------+--------------------------------------------+
| **Variable**                                          | **Beschreibung** | **Einheit** | **Zeitpunkt** | **Hinweis**                                |
+:======================================================+:=================+:============+:==============+:===========================================+
| Zeitpunkt der letzten Datenerhebung (last seen alive) |                  |             | EdB           |                                            |
+-------------------------------------------------------+------------------+-------------+---------------+--------------------------------------------+
| Patient verstorben                                    |                  |             | EdB           |                                            |
+-------------------------------------------------------+------------------+-------------+---------------+--------------------------------------------+
| Todesdatum                                            |                  |             | EdB           | Erscheint, wenn Patient:in verstorben = Ja |
+-------------------------------------------------------+------------------+-------------+---------------+--------------------------------------------+
| Grund                                                 |                  |             | EdB           | Erscheint, wenn Patient:in verstorben = Ja |
+-------------------------------------------------------+------------------+-------------+---------------+--------------------------------------------+

# Demographie

+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+
| **Variable**                | **Beschreibung**                        | **Einheit** | **Zeitpunkt** | **Hinweis**                                             |
+:============================+:========================================+:============+:==============+:========================================================+
| Zentrumseigene Patienten ID |                                         |             | L             |                                                         |
+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+
| Episode                     | Anzahl der Aufnahmen auf die Warteliste |             | L             | Für eine ausführliche Erklärung: siehe Reiter "Episode" |
+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+
| Geburtsdatum (Monat)        |                                         | Monat       | L             |                                                         |
+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+
| Geburtsdatum (Jahr)         |                                         | Jahr        | L             |                                                         |
+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+
| Geschlecht                  |                                         |             | L             | Genetisch determiniertes Geschlecht angeben             |
+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+
| Datum der Listung           |                                         |             | L             |                                                         |
+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+
| Datum der Transplantation   |                                         |             | Tx            | Erscheint, wenn Neuer Status = transplantiert           |
+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+
| Blutgruppe                  |                                         |             | L             |                                                         |
+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+
| Rhesusfaktor                |                                         |             | L             |                                                         |
+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+
| Größe                       |                                         | cm          | L             |                                                         |
+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+
| Gewicht                     |                                         | kg          | L, Tx         |                                                         |
+-----------------------------+-----------------------------------------+-------------+---------------+---------------------------------------------------------+

# Niere

+------------------------------+------------------+-------------+---------------+-----------------------------+
| **Variable**                 | **Beschreibung** | **Einheit** | **Zeitpunkt** | **Hinweis**                 |
+:=============================+:=================+:============+:==============+:============================+
| Nierenersatzverfahren 2w vor |                  |             | L, Tx         | 2w = 2 Wochen vor L oder Tx |
+------------------------------+------------------+-------------+---------------+-----------------------------+

# Laborwerte

| Variable | Beschreibung | Einheit | Zeitpunkt | Hinweis |
|----|----|----|----|----|
| Natrium |  | mmol/l | L, Tx |  |
| Bilirubin |  | mg/dl ODER $\mu$mol/l | L, Tx |  |
| Serumkreatinin |  | mg/dl ODER mmol/l | L, Tx |  |
| Albumin |  | mg/dl | L, Tx |  |
| INR | International Normalized Ratio |  | L, Tx |  |
| PRA | Panel Reactive Antibodies | \% | L, Tx |  |

# Sonstige medikamentöse Therapie

+------------------------------------------------+-------------------------------------------+-------------+---------------+--------------------------------------------------------------------------------------------------------+
| **Variable**                                   | **Beschreibung**                          | **Einheit** | **Zeitpunkt** | Medikamente (die bekanntesten, aber nicht ausschließlich)                                              |
+:===============================================+:==========================================+:============+:==============+:=======================================================================================================+
| Marcumar - Therapie / Vitamin K - Antagonisten |                                           |             | L, Tx         | -   Phenprocoumon                                                                                      |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Warfarin                                                                                           |
+------------------------------------------------+-------------------------------------------+-------------+---------------+--------------------------------------------------------------------------------------------------------+
| DOAK                                           | Direkte orale Antikoagulanzien            |             | L, Tx         | -   Dabigatran (Pradaxa®) Ximelagatran (Exanta®, orales Prodrug von Melagatran, nicht mehr zugelassen) |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Apixaban (Eliquis®)                                                                                |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Edoxaban (Lixiana®)                                                                                |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Otamixaban                                                                                         |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Rivaroxaban (Xarelto®)                                                                             |
+------------------------------------------------+-------------------------------------------+-------------+---------------+--------------------------------------------------------------------------------------------------------+
| $\beta$-Blocker                                |                                           |             | L, Tx         | -   Acebutolol                                                                                         |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Alprenolol                                                                                        |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    **Atenolol**                                                                                      |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Betaxolol                                                                                         |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   **Bisoprolol**                                                                                     |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Bunolol                                                                                            |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Carteolol                                                                                         |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    **Carvedilol**                                                                                    |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Celiprolol                                                                                        |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    **Esmolol**                                                                                       |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Labetalol                                                                                         |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Levobunolol                                                                                       |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Metipranolol                                                                                      |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    **Metoprolol**                                                                                    |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Nadolol                                                                                            |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Oxprenolol                                                                                        |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Pindolol                                                                                          |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    **Propranolol**                                                                                   |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    **Sotalol**                                                                                       |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Timolol                                                                                           |
+------------------------------------------------+-------------------------------------------+-------------+---------------+--------------------------------------------------------------------------------------------------------+
| Sartane                                        |                                           |             | L, Tx         | -   Azilsartan                                                                                         |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Candesartan                                                                                        |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Eprosartan                                                                                         |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Irbesartan                                                                                         |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Losartan                                                                                           |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Olmesartan                                                                                         |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Telmisartan                                                                                        |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Valsartan                                                                                          |
+------------------------------------------------+-------------------------------------------+-------------+---------------+--------------------------------------------------------------------------------------------------------+
| Diuretika                                      |                                           |             | L, Tx         | -   Thiazidartige Entwässerungsmittel (**Xipamid,** Chlortalidon)                                      |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Kaliumsparende Diuretika (Triamteren, Amilorid)                                                    |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Schleifendiuretika (**Furosemid, Torasemid**)                                                      |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Osmodiuretika (Mannit, Glycerin, Sorbit)                                                           |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Carboanhydrase-Hemmer (Acetazolamid)                                                               |
+------------------------------------------------+-------------------------------------------+-------------+---------------+--------------------------------------------------------------------------------------------------------+
| Aldosteron                                     |                                           |             | L, Tx         | -   Spironolacton                                                                                      |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Eplerenon                                                                                         |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -    Finerenon                                                                                         |
+------------------------------------------------+-------------------------------------------+-------------+---------------+--------------------------------------------------------------------------------------------------------+
| ARNI                                           | Angiotensin-Rezeptor-Neprilysin-Inhibitor |             | L, Tx         | -   Acubitril                                                                                          |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Valsartan (Entresto®)                                                                              |
+------------------------------------------------+-------------------------------------------+-------------+---------------+--------------------------------------------------------------------------------------------------------+
| SGLT2                                          |                                           |             | L, Tx         | -   Canagliflozin                                                                                      |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Dapagliflozin                                                                                      |
|                                                |                                           |             |               |                                                                                                        |
|                                                |                                           |             |               | -   Empagliflozin                                                                                      |
+------------------------------------------------+-------------------------------------------+-------------+---------------+--------------------------------------------------------------------------------------------------------+

# Sonstige Parameter

+------------------------------------------------+------------------------------------+--------------------------------------+-------------------+---------------------------+
| **Variable**                                   | **Beschreibung**                   | **Einheit**                          | **Zeitpunkt**     | **Hinweis**               |
+:===============================================+:===================================+:=====================================+:==================+:==========================+
| Mechanische Beatmung                           |                                    |                                      | L, Tx             |                           |
+------------------------------------------------+------------------------------------+--------------------------------------+-------------------+---------------------------+
| Inotropikatherapie                             |                                    |                                      | L, Tx             |                           |
+------------------------------------------------+------------------------------------+--------------------------------------+-------------------+---------------------------+
| PCWP                                           | Pulmonary Capillary Wedge Pressure | mmHg                                 | L, Tx             |                           |
+------------------------------------------------+------------------------------------+--------------------------------------+-------------------+---------------------------+
| CI                                             | Cardiac Index                      | l/min/m2                             | L, Tx             |                           |
+------------------------------------------------+------------------------------------+--------------------------------------+-------------------+---------------------------+
| PVR                                            |                                    | Wood Einheiten ODER dyn x sec x cm-5 | L, Tx             |                           |
+------------------------------------------------+------------------------------------+--------------------------------------+-------------------+---------------------------+
| LVEF                                           | Left Ventricular Ejection Fraction | \%                                   | L, Tx             |                           |
+------------------------------------------------+------------------------------------+--------------------------------------+-------------------+---------------------------+
| Stationäre Behandlungen wegen Herzinsuffizienz |                                    | Anzahl im letzten Jahr               | L                 | innerhalb 12 Monate vor L |
+------------------------------------------------+------------------------------------+--------------------------------------+-------------------+---------------------------+
| Stationäre Behandlungen wegen Herzinsuffizienz |                                    |                                      | zwischen L und Tx | maximal bis Tx            |
+------------------------------------------------+------------------------------------+--------------------------------------+-------------------+---------------------------+

# Begleiterkrankungen

+--------------------------------------------------+----------------------------------------+-------------+---------------+-------------+
| **Variable**                                     | **Beschreibung**                       | **Einheit** | **Zeitpunkt** | **Hinweis** |
+:=================================================+:=======================================+:============+:==============+:============+
| Diabetes Mellitus                                |                                        |             | L             |             |
+--------------------------------------------------+----------------------------------------+-------------+---------------+-------------+
| Diabetische Sekundärkomplikation Polyneuropathie |                                        |             | L             |             |
+--------------------------------------------------+----------------------------------------+-------------+---------------+-------------+
| Diabetische Sekundärkomplikation Auge            |                                        |             | L             |             |
+--------------------------------------------------+----------------------------------------+-------------+---------------+-------------+
| PAVK                                             |                                        |             | L             |             |
+--------------------------------------------------+----------------------------------------+-------------+---------------+-------------+
| CAVK                                             |                                        |             | L             |             |
+--------------------------------------------------+----------------------------------------+-------------+---------------+-------------+
| Anzahl der kardialen Voroperationen              |                                        |             | L             |             |
+--------------------------------------------------+----------------------------------------+-------------+---------------+-------------+
| ICD                                              | Implantable Cardioverter-Defibrillator |             | L             |             |
+--------------------------------------------------+----------------------------------------+-------------+---------------+-------------+
| Schockabgabe                                     |                                        |             | L             |             |
+--------------------------------------------------+----------------------------------------+-------------+---------------+-------------+
| CRT                                              | Cardiac Resynchronization Therapy      |             | L, Tx         |             |
+--------------------------------------------------+----------------------------------------+-------------+---------------+-------------+
| Z.n. Schlaganfall                                |                                        |             | L             |             |
+--------------------------------------------------+----------------------------------------+-------------+---------------+-------------+

# Voroperationen / Eingriffe

+-----------------------------------------------+------------------+-------------+---------------+----------------------------------------------+
| **Variable**                                  | **Beschreibung** | **Einheit** | **Zeitpunkt** | **Hinweis**                                  |
+:==============================================+:=================+:============+:==============+:=============================================+
| Kardiale Voroperationen                       |                  |             | L, Tx         |                                              |
+-----------------------------------------------+------------------+-------------+---------------+----------------------------------------------+
| Kardiale Voroperationen - angeborene Vitien   |                  |             | L, Tx         | Erscheint, wenn Kardiale Voroperationen = Ja |
+-----------------------------------------------+------------------+-------------+---------------+----------------------------------------------+
| Kardiale Voroperationen - Koronarchirurgie    |                  |             | L, Tx         | Erscheint, wenn Kardiale Voroperationen = Ja |
+-----------------------------------------------+------------------+-------------+---------------+----------------------------------------------+
| Kardiale Voroperationen - permanente MCS      |                  |             | L, Tx         | Erscheint, wenn Kardiale Voroperationen = Ja |
+-----------------------------------------------+------------------+-------------+---------------+----------------------------------------------+
| Z.n. OP/Intervention an der Aortenklappe      |                  |             | L, Tx         | Erscheint, wenn Kardiale Voroperationen = Ja |
+-----------------------------------------------+------------------+-------------+---------------+----------------------------------------------+
| Z.n. OP/Intervention an der Mitralklappe      |                  |             | L, Tx         | Erscheint, wenn Kardiale Voroperationen = Ja |
+-----------------------------------------------+------------------+-------------+---------------+----------------------------------------------+
| Z.n. OP/Intervention an der Pulmonalklappe    |                  |             | L, Tx         | Erscheint, wenn Kardiale Voroperationen = Ja |
+-----------------------------------------------+------------------+-------------+---------------+----------------------------------------------+
| Z.n. OP/Intervention an der Trikuspidalklappe |                  |             | L, Tx         | Erscheint, wenn Kardiale Voroperationen = Ja |
+-----------------------------------------------+------------------+-------------+---------------+----------------------------------------------+

# Mechanische Kreislaufunterstützung - seit Listung

+--------------------------------+------------------+-------------+-------------------------+-------------+
| **Variable**                   | **Beschreibung** | **Einheit** | **Zeitpunkt**           | **Hinweis** |
+:===============================+:=================+:============+:========================+:============+
| MCS dauerhaft - Permanente MCS |                  |             | zwischen L und Tx / EdB |             |
+--------------------------------+------------------+-------------+-------------------------+-------------+
| Datum der Implantation         |                  |             | zwischen L und Tx / EdB |             |
+--------------------------------+------------------+-------------+-------------------------+-------------+

# Spenderdaten

Erscheint, wenn Neuer Status = transplantiert.

+-----------------------------------------------+------------------+-------------+---------------+-------------+
| **Variable**                                  | **Beschreibung** | **Einheit** | **Zeitpunkt** | **Hinweis** |
+:==============================================+:=================+:============+:==============+:============+
| Geschlecht                                    |                  |             | Tx            |             |
+-----------------------------------------------+------------------+-------------+---------------+-------------+
| Gewicht                                       |                  | kg          | Tx            |             |
+-----------------------------------------------+------------------+-------------+---------------+-------------+
| Größe                                         |                  | cm          | Tx            |             |
+-----------------------------------------------+------------------+-------------+---------------+-------------+
| Spenderalter                                  |                  | Jahre       | Tx            |             |
+-----------------------------------------------+------------------+-------------+---------------+-------------+
| Komplette Ischämiezeit                        |                  | Minuten     | Tx            |             |
+-----------------------------------------------+------------------+-------------+---------------+-------------+
| Zeit außerhalb des Körpers (out of body time) |                  | Minuten     | Tx            |             |
+-----------------------------------------------+------------------+-------------+---------------+-------------+
| Perfusionssystem OCS                          |                  |             | Tx            |             |
+-----------------------------------------------+------------------+-------------+---------------+-------------+
| Perfusionssystem Xvivo                        |                  |             | Tx            |             |
+-----------------------------------------------+------------------+-------------+---------------+-------------+

# Perioperativer Verlauf

Erscheint, wenn Neuer Status = transplantiert.

+-------------------------------------------+------------------+-------------+---------------+---------------------+
| **Variable**                              | **Beschreibung** | **Einheit** | **Zeitpunkt** | **Hinweis**         |
+:==========================================+:=================+:============+:==============+:====================+
| System Infektion                          |                  |             | Tx            |                     |
+-------------------------------------------+------------------+-------------+---------------+---------------------+
| Blutung                                   |                  |             | Tx            |                     |
+-------------------------------------------+------------------+-------------+---------------+---------------------+
| Apoplex                                   |                  |             | Tx            |                     |
+-------------------------------------------+------------------+-------------+---------------+---------------------+
| Apoplex / thomboembolische Komplikationen |                  |             | Tx            | bis 30 Tage nach Tx |
+-------------------------------------------+------------------+-------------+---------------+---------------------+
| Allograftversagen                         |                  |             | Tx            | bis 30 Tage nach Tx |
+-------------------------------------------+------------------+-------------+---------------+---------------------+
